name: Cypress Test

on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
        partition: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install Dependencies
        run: npm install

      - name: Cypress.io Install
        uses: cypress-io/github-action@v4
        with:
          runTests: false  # Only install Cypress, don't run tests yet

      - name: Run Cypress Tests on ${{ matrix.browser }} - Partition ${{ matrix.partition }}
        run: |
          if [ ${{ matrix.partition }} == 1 ]; then
            npx cypress run --browser ${{ matrix.browser }} --headless --spec "cypress/e2e/login.cy.js,cypress/e2e/Dashboard/**.cy.js"
          else
            npx cypress run --browser ${{ matrix.browser }} --headless --spec "cypress/e2e/settings.cy.js,cypress/e2e/Login/**.cy.js"
          fi
