name: Cypress Test

on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
        partition: [Dashboard, Login]  # Partition by folder
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install Dependencies
        run: npm install

      - name: Cypress.io Install
        uses: cypress-io/github-action@v4
        with:
          runTests: false  # Only install Cypress, don't run tests yet

      - name: Run Cypress Tests on ${{ matrix.browser }} - ${{ matrix.partition }}
        run: |
          if [ ${{ matrix.partition }} == "Dashboard" ]; then
            npx cypress run --browser ${{ matrix.browser }} --headless --spec "cypress/e2e/Dashboard/*.cy.js"
          elif [ ${{ matrix.partition }} == "Login" ]; then
            npx cypress run --browser ${{ matrix.browser }} --headless --spec "cypress/e2e/Login/*.cy.js"
          fi
