name: Cypress Test

on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
        container: [1, 2, 3]  # Run 3 containers in parallel

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install Dependencies
        run: npm install

      - name: Cypress.io Install
        uses: cypress-io/github-action@v4
        with:
          runTests: false  # Only install, don’t run tests yet

      - name: Run Cypress Tests in Parallel on ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }} --headless --env split=true
